name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout Specs
      uses: actions/checkout@v2
      with:
        repository: CocoaPods/Specs
        path: _specs
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundler
      run: |
        bundle config path vendor/bundle
        bundle install --jobs=4
    - name: Build indices
      run: |
        Scripts/build.sh
    - name: Deploy to Pages
      if: github.event_name == 'schedule'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_specs/_site
        cname: cdn.cocoapods.org
        force_orphan: true
    - uses: actions/upload-artifact@v2
      if: github.event_name != 'schedule'
      with:
        name: site
        path: ./_specs/_site/*

on:
  push:
  schedule:
    - cron:  '* * * * *' # max frequency specified because the actual frequency is determined by GH Actions rate limit  
      branches:
      - main